list=['Mango','Mulberry','Guava','Papaya','peach','Banana']
print("length of list:",len(list))
print("first element:", list[0])
print("last element:", list[-1])
list.append('Strawberry')
print('Updated list:',list)
list.remove('Banana')
print('Updated list:',list)
list.sort()
print('sorted list:',list)
list.pop(1)
print('Updated list:',list)
list.reverse()
print('Reversed list:',list)
print('Multiplication on list:',list*2)